# Generated by Django 5.0.4 on 2024-07-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_booking_booking_number_alter_room_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingrule',
            name='is_high_season',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(default='5b679f41-587', max_length=12, unique=True),
        ),
    ]
