# Generated by Django 5.0.4 on 2024-07-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_booking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(default='5b4ddc07-b3b', max_length=12, unique=True),
        ),
    ]
