# Generated by Django 5.0.4 on 2024-07-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_pricingrule_delete_seasonprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(default='c14a39c6-12a', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
